Use inspections instead of string parsing for class discovery
bit-bots/dynamic_stack_decider pull request #38
Opened 2021-01-07 11:48 UTC by timonegk

## Proposed changes
This pull requests changes the class discovery in the dynamic stack decider to use python inspections instead of string parsing.

## Necessary checks
- [x] Update package version
- [x] Run `catkin build`
- [x] Write documentation
- [ ] Create issues for future work
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

2021-01-07 14:21 UTC, ftsell approved these changes
I can't currently test this but it looks good

2021-04-20 10:18 UTC, ftsell requested changes
In general I like the changes because it removes the complexity and instability from manually parsing python code. I have also tested the changes and they work on my machine.

I do have some minor comments thoug. Please address them

2021-04-20 10:18 UTC, lilioid commented on dynamic_stack_decider/src/dynamic_stack_decider/dsd.py
>  import re
`os` and `re` are now unused imports. Please remove them

2021-04-20 10:18 UTC, lilioid commented on dynamic_stack_decider/src/dynamic_stack_decider/dsd.py
> +    base_module = path.split("/src/")[-1].replace('/', '.')
You could also use pathlib to do these path operations in a safer way. But since we are only doing one such operation i'd say it's fine.

2021-04-20 10:18 UTC, ftsell commented on dynamic_stack_decider/src/dynamic_stack_decider/dsd.py
> +            elements.update(inspect.getmembers(module, lambda m: inspect.isclass(m) and inspect.getmodule(m) == module))
I would like to have an explaining comment here
```suggestion
            # put all classes which are defined directly in the target module (not imported) into results
            elements.update(inspect.getmembers(module, lambda m: inspect.isclass(m) and inspect.getmodule(m) == module))
```

2021-04-20 10:36 UTC, ftsell approved these changes

2021-04-20 10:38 UTC, timonegk commented on dynamic_stack_decider/src/dynamic_stack_decider/dsd.py
> +    base_module = path.split("/src/")[-1].replace('/', '.')
In general, I agree. But in this case, if I see it correctly, only the `replace` coud be replaced with something like `'.'.join(path.parts)`, but the `split` cannot be done by pathlib. So I don't think it's much of an improvement.

2021-04-20 10:48 UTC, merged