Fix discover_modules
bit-bots/dynamic_stack_decider pull request #45
Opened 2021-04-26 10:07 UTC by ftsell

## Proposed changes
This PR includes two fixes. Their description can be extracted from the respective commit messages.

## Related issues
I have already mentioned the necessity of the fix in 2c9de3ef06aad42e93ed4f10766367c22d54924d with @timonegk 

## Necessary checks
- [x] Update package version
- [x] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

2021-04-27 19:15 UTC, timonegk approved these changes

2021-04-27 19:25 UTC, timonegk requested changes
The changes do not work when there are two modules with the same name, for example in teh body behavior, there is `actions/timer.py` and `decisions/timer.py`. Even though `discover_elements` is called once with the path to the `actions` folder and once with the path for the `decisions` folder, the `actions/timer.py` is used both times. 
To reproduce, run `roslaunch bitbots_bringup visualization.launch`.

2021-04-28 12:31 UTC, ftsell commented
> The changes do not work when there are two modules with the same name, for example in teh body behavior, there is `actions/timer.py` and `decisions/timer.py`. Even though `discover_elements` is called once with the path to the `actions` folder and once with the path for the `decisions` folder, the `actions/timer.py` is used both times.
> To reproduce, run `roslaunch bitbots_bringup visualization.launch`.

I cannot reproduce this. It might be due to the two additional changes I have since introduced.

2021-04-28 12:47 UTC, timonegk approved these changes

2021-04-28 12:48 UTC, merged