Add documentation for the DSD
bit-bots/dynamic_stack_decider pull request #51
Opened 2021-05-13 14:22 UTC by timonegk

## Proposed changes
This pull request adds the long-awaited documentation for the DSD.

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [x] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

2021-05-13 15:26 UTC, ftsell submitted a review, later dismissed

2021-05-14 08:44 UTC, SammyRamone requested changes

2021-05-14 08:44 UTC, SammyRamone commented on README.md
> +The framework is also described in more depth in [ASDS – Active Self Deciding Stack: A Lightweight Approach for Dynamic Decision Making](https://www.researchgate.net/profile/Martin_Poppinga/publicati
we have a newer better paper
https://www.researchgate.net/publication/350168815_DSD_-_Dynamic_Stack_Decider_A_Lightweight_Decision_Making_Framework_for_Robots_and_Software_Agents

2021-05-14 09:51 UTC, SammyRamone approved these changes

2021-05-14 09:52 UTC, merged